Django/epoll/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path("", views.home_view, name="home"),
	path('login/', views.login_view, name="login"),
	path('register/', views.register_view, name="register"),
	path('dashboard/', views.dashboard_view, name="dashboard"),
	path('logout/', views.logout_view, name='logout'),
	path('position/', views.position_view, name='position'),
	path('candidate/<int:pos>/', views.candidate_view, name="candidate"),
	path('candidate/detail/<int:id>/', views.candidateDetail_view, name="detail"),
	path('results/', views.result_view, name='result'),
	path('changePassword/', views.changePassword_view, name='changePassword'),
	path('editProfile/', views.editProfile_view, name='editProfile'),
]

Django/votingSystem/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("epoll.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/epoll/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Position(models.Model):
	title = models.CharField(max_length=50, unique=True)

	def __str__(self):
		return f"{self.title}"


class Candidate(models.Model):
	name = models.CharField(max_length=50)
	no_votes=models.IntegerField(default=0, editable=False)
	position = models.ForeignKey(Position, on_delete=models.CASCADE)
	image = models.ImageField(verbose_name="Candidate Picture", upload_to='media/images/')

	def __str__(self):
		return f'{self.name} - {self.position.title}'


class VoteStatus(models.Model):
	user=models.ForeignKey(User, on_delete=models.CASCADE)
	position=models.ForeignKey(Position, on_delete=models.CASCADE)
	status=models.BooleanField(default=False)

	def __str__(self):
		return f"{self.user} - {self.position.title} - {self.status}"

Django/epoll/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(forms.ModelForm):
	email = forms.EmailField()
	confirm_password = forms.CharField(max_length=100, widget=forms.PasswordInput)
	class Meta:
		model = User
		fields = ["username", "first_name", "last_name", "email", "password"]
		widgets = {
            'password': forms.PasswordInput,
        }
		
class ChangeForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username', 'first_name', 'last_name', 'email']

Django/epoll/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import login,logout,authenticate, update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.decorators import login_required
from .models import Candidate, VoteStatus, Position
from .forms import RegisterForm, ChangeForm 


# Create your views here.
def home_view(request):
	return render(request, "epoll/home.html")

def login_view(request):
	if request.method == "POST":
		username = request.POST["username"]
		password = request.POST["password"]
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return redirect("dashboard")
		else:
			return render(request, "epoll/login.html", {"message": "Invalid credentials."})
	else:
		return render(request, "epoll/login.html")

def register_view(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['password'] == cd['confirm_password']:
                obj = form.save(commit=False)
                obj.set_password(obj.password)
                obj.save()
                messages.success(request, '.تم التسجيل بنجاح ')
                return redirect('home')
            else:
                return render(request, "epoll/register.html", {'form':form,'note':'password must match'})
    else:
        form = RegisterForm()

    return render(request, "epoll/register.html", {'form':form})



@login_required
def dashboard_view(request):
	return render(request, "epoll/dashboard.html")

@login_required
def logout_view(request):
	logout(request)
	return redirect("home")

@login_required
def position_view(request):
	position = Position.objects.all()
	return render(request, 'epoll/position.html', {"obj": position})

@login_required
def candidate_view(request, pos):
	obj=get_object_or_404(Position, pk=pos)
	if request.method == 'POST':
		temp = VoteStatus.objects.get_or_create(user=request.user, position=obj)[0]
		if temp.status == False:
			temp2=Candidate.objects.get(pk=request.POST.get(obj.title))
			temp2.no_votes+=1
			temp2.save()
			temp.status=True
			temp.save()
			return HttpResponseRedirect("/position/")
		else:
			messages.success(request, "لقد قمت بالتصويت بالفعل لهذا المنصب!")
			return render(request, 'epoll/candidate.html', {'obj': obj})
	else:
		return render(request, 'epoll/candidate.html', {'obj': obj})


@login_required
def candidateDetail_view(request, id):
	obj=get_object_or_404(Candidate, pk=id)
	return render(request, 'epoll/c_detail.html', {'obj': obj})

@login_required
def result_view(request):
	obj = Candidate.objects.all().order_by('position', '-no_votes')
	return render(request, "epoll/results.html", {'obj': obj})	

@login_required
def changePassword_view(request):
	if request.method == "POST":
		form = PasswordChangeForm(user=request.user, data=request.POST)
		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect('dashboard')
	else:
		form = PasswordChangeForm(user=request.user)

	return render(request, "epoll/password.html", {'form': form})		

@login_required
def editProfile_view(request):
	if request.method == 'POST':
		form = ChangeForm(request.POST, instance=request.user)
		if form.is_valid():
			form.save()
			return redirect('dashboard')
	else:
		form = ChangeForm(instance=request.user)
	return render(request, 'epoll/edit_profile.html', {'form': form})

Django/epoll/templates/epoll/c_detail.html
{% extends "epoll/layout.html" %} %} {% block content %}
<div class="jumbotron">
  <table class="table">
    <tr>
      <td>
        <img
          src="{{ obj.image.url }}"
          width="220"
          height="280"
          class="img-fluid"
        />
      </td>
    </tr>
    <tr>
      <td>
        <p>Name: {{ obj.name }}</p>
      </td>
    </tr>
  </table>
</div>

{% endblock %}

Django/epoll/templates/epoll/candidate.html
{% extends "epoll/layout.html" %}

{% block title %}Candidate{% endblock %}

{% block content %}

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-danger" role="alert">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <h2>Available Candidates of {{ obj.title }}</h2>
  <form action="" method="POST">
    {% csrf_token %}
    {% for c in obj.candidate_set.all %}
     <div class="custom-control custom-radio">
      <input type="radio" id="id_{{c.id}}" name="{{ c.position}}" value="{{c.id}}" class="custom-control-input" required>
      <label class="custom-control-label" for="id_{{c.id}}">{{c.name}} <a href="{% url 'detail' c.id %}">Detail</a></label>
    </div>
    {% empty %}
      <p>No Candidates Available</p>
    {% endfor %}
    <br><input type="submit" class="btn btn-outline-success btn-sm" value="VOTE">
  </form>
  <br><p><a href="{% url 'position' %}">Back to Poll</a></p>
{% endblock %}

Django/epoll/templates/epoll/dashboard.html
{% extends 'epoll/layout.html' %} {%block content %}
<div class="jumbotron" id="dash">
  <h2>{{request.user.get_full_name }},مرحبا</h2>
  <h3><a href="{% url 'position'%}">إضغط هنا للتصويت</a></h3>
  <h3><a href="{% url 'result' %}">إضغط هنا لمعرفة النتيجة</a></h3>
</div>
{% endblock %}

Django/epoll/templates/epoll/edit_profile.html
{% extends "epoll/layout.html" %}

{% block title %}Update Profile{% endblock %}

{% block content %}
  <div class="jumbotron">
    <h2>Update Profile</h2>

    <form action="" method="POST">
      {% csrf_token %}
      {{form.as_p}}

      {% for field in form %}
        <div class="form-group">
          {% if field.errors %}
            {% for error in field.errors %}
              <ul>
                <li>{{error}}</li>
              </ul>
            {% endfor %}
          {% endif %}
          {% if field.help_text %}
            <small class="form-text text-muted">{{field.help_text}}</small>
          {% endif %}
        </div>
      {% endfor %}
      <input type="submit" class="btn btn-primary btn-sm" value="Update">
    </form>
  </div>

{% endblock %}

Django/epoll/templates/epoll/home.html
{% extends "epoll/layout.html"%} Electronic Ballot System {% block content %}

<div class="jumbotron" id="home">
  {% if messages %} {% for message in messages %}
  <div class="alert alert-success" role="alert">{{ message }}</div>
  {% endfor %} {% endif %}
  <h1>وقيت باش تقيد</h1>
  <h3>صوتك يهمنا</h3>
</div>
{% load static %}
<!-- Navbar Start -->
<div class="container-fluid p-0">
  <nav
    class="navbar navbar-expand-lg bg-white navbar-light py-3 py-lg-0 px-lg-5"
  >
    <link href="{% static ''%}epoll/css/style.css" rel="stylesheet" />
    <button
      type="button"
      class="navbar-toggler"
      data-toggle="collapse"
      data-target="#navbarCollapse"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <!-- <div
      class="collapse navbar-collapse justify-content-between px-lg-3"
      id="navbarCollapse"
    >
      <a href="" class="btn btn-primary py-2 px-4 d-none d-lg-block"
        >تسجيل الدخول</a
      >
      <a href="" class="btn btn-primary py-2 px-4 d-none d-lg-block">تسجيل</a>
      <div class="navbar-nav mx-auto py-0">
        <a href="contact.html" class="nav-item nav-link">للإتصال</a>
        <a href="#statics" class="nav-item nav-link">إحصائيات</a>
        <a href="#vote" class="nav-item nav-link">تصويت</a>
        <a href="about.html" class="nav-item nav-link">معلومات عنا</a>
        <a href="index.html" class="nav-item nav-link active"
          >الصفحة الرئيسية</a
        >
      </div>
    </div> -->
    <a href="index.html" class="navbar-brand ml-lg-3">
      <div class="redi"></div>
    </a>
  </nav>
</div>
<!-- Navbar End -->

<!-- Header Start -->
<div
  class="jumbotron jumbotron-fluid position-relative overlay-bottom"
  style="margin-bottom: 90px"
>
  <!-- <div class="container text-center my-5 py-5">
    <h1 class="text-white mt-4 mb-4">ابحث هنا</h1>
    <h1 class="text-white display-1 mb-5">وق باش تقيد</h1>
    <div class="mx-auto mb-5" style="width: 100%; max-width: 600px">
      <div class="input-group">
        <div class="input-group-append">
          <button class="btn btn-secondary px-4 px-lg-5">ابحث</button>
        </div>
        <input
          type="text"
          class="form-control border-light"
          style="padding: 30px 25px"
          placeholder="                                                                            ابحث هنا"
        />
      </div>
    </div>
  </div>
</div> -->

  <!-- Feature Start -->
  <div class="container-fluid bg-image" style="margin: 90px 0">
    <div class="container">
      <div class="row">
        <div class="col-lg-7 my-5 pt-5 pb-lg-5">
          <div class="section-title position-relative mb-4">
            <h1 class="display-4">: التفاصيل</h1>
          </div>
          <p class="mb-4 pb-2 align">
            الهيئة العليا المستقلة للانتخابات هيئة عمومية مستقلة ودائمة تتمتع
            بالشخصية المعنوية والاستقلال الإداري والمالي مقرها تونس العاصمة
          </p>
          <div class="row pt-3 mx-0">
            <div class="col-3 px-0">
              <div class="bg-success text-center p-4">
                <h1 class="text-white size" data-toggle="counter-up">5</h1>
                <h6 class="text-uppercase text-white">عدد المرشحين</h6>
              </div>
            </div>
            <div class="col-3 px-0">
              <div class="bg-primary text-center p-4">
                <h1 class="text-white size" data-toggle="counter-up">700000</h1>
                <h6 class="text-uppercase text-white">عدد الناخبين</h6>
              </div>
            </div>
            <div class="col-3 px-0">
              <div class="bg-secondary text-center p-4">
                <h1 class="text-white size" data-toggle="counter-up">
                  1000000
                </h1>
                <h6 class="text-uppercase text-white">عدد المسجلين</h6>
              </div>
            </div>
          </div>
        </div>

        <div class="col-lg-5" style="min-height: 500px">
          <div class="position-relative h-100">
            <img
              class="position-absolute w-100 h-100"
              src="{% static ''%}epoll/img/image3.jpg"
              style="object-fit: cover"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Feature Start -->
  <div class="row">
    <div class="column">
      <img
        src="{% static ''%}epoll/img/فاروق بوعسكر القايدي.jpg"
        alt="Snow"
        style="width: 100%"
      />
      
<a class="btn btn-primary">تحميل</a>
    </div>

      <img
        class="column"
        src="{% static ''%}epoll/img/ماهر الجديدي.jpg"
        alt="ماهر الجديدي"
        style="width: 100%"
      />
      <a class="btn btn-primary">تحميل</a>

      <img
        class="column"
        src="{% static ''%}epoll/img/محمد التليلي منصري.jpg"
        alt="محمد التليلي منصري"
        style="width: 100%"
      />
      <a class="btn btn-primary">تحميل</a>

      <img
        class="column"
        src="{% static ''%}epoll/img/محمود الواعر.jpg"
        alt="محمود الواعر"
        style="width: 100%"
      />
      <a class="btn btn-primary">تحميل</a>

      <img
        class="column"
        src="{% static ''%}epoll/img/محمد نوفل فريخة.jpg"
        alt=" محمد نوفل فريخة"
        style="width: 100%"
      />
      <a class="btn btn-primary "href="/cv.pdf" >تحميل</a>


      <!-- Testimonial Start -->
      <div class="container-fluid bg-image py-5" style="margin: 90px 0">
        <div class="container py-5">
          <div class="row align-items-center">
            <div class="col-lg-7">
              <div class="owl-carousel testimonial-carousel">
                <div class="bg-white p-5">
                  <i class="fa fa-3x fa-quote-left text-primary mb-4"></i>
                  <p class="align">
                    احصائيّات قبول الترشحات لانتخاب أعضاء مجلس نواب الشعب 2022
                    في يومها الحادي عشر والأخير بتاريخ الخميس 27 أكتوبر 2022 بعد
                    غلق المكاتب الرئيسية للترشحات على الساعة السادسة مساء
                  </p>
                  <div class="d-flex flex-shrink-0 align-items-center mt-4">
                    <img
                      class="img-fluid mr-4"
                      src="{% static ''%}epoll/img/logo.png"
                      alt="image"
                      style="width: 70%"
                    />

                    <h5>في 2022/10/28</h5>
                  </div>
                </div>
                <div class="bg-white p-5">
                  <i class="fa fa-3x fa-quote-left text-primary mb-4"></i>
                  <p class="align">
                    مكاتب تحيين التسجيل القارة للفترة الثانية الاستثنائية
                    للتحيين من 28 أكتوبر 2022 إلى غاية 20 نوفمبر
                  </p>
                  <div class="d-flex flex-shrink-0 align-items-center mt-4">
                    <img
                      class="img-fluid mr-4"
                      src="{% static ''%}epoll/img/logo.png"
                      alt="image"
                      style="width: 70%"
                    />

                    <h5>في 2022/10/27</h5>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-5 mb-5 mb-lg-0">
              <div class="section-title position-relative mb-4">
                <h1 class="align display-4">: اخر المستجدات</h1>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Testimonial Start -->

      <!-- Contact Start -->
      <div class="container-fluid py-5">
        <div class="container py-5">
          <div class="row align-items-center">
            <div class="col-lg-5 mb-5 mb-lg-0">
              <div
                class="bg-light d-flex flex-column justify-content-center px-5"
                style="height: 450px"
              >
                <div class="d-flex align-items-center mb-5">
                  <div class="btn-icon bg-primary mr-4">
                    <i class="fa fa-2x fa-map-marker-alt text-white"></i>
                  </div>
                  <div class="mt-n1">
                    <h4>موقعنا</h4>
                    <p class="m-0">
                      نهج جزيرة سردينيا - عدد 05 - حدائق البحيرة -1053 تونس
                    </p>
                  </div>
                </div>
                <div class="d-flex align-items-center mb-5">
                  <div class="btn-icon bg-secondary mr-4">
                    <i class="fa fa-2x fa-phone-alt text-white"></i>
                  </div>
                  <div class="mt-n1">
                    <h4>اتصل بنا</h4>
                    <p class="m-0">(+216) 93 234 428</p>
                  </div>
                </div>
                <div class="d-flex align-items-center">
                  <div class="btn-icon bg-warning mr-4">
                    <i class="fa fa-2x fa-envelope text-white"></i>
                  </div>
                  <div class="mt-n1">
                    <h4>ارسل لنا عبر البريد الإلكتروني</h4>
                    <p class="m-0">harounbouriga99@gmail.com</p>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-lg-7">
              <div class="section-title position-relative mb-4">
                <h6
                  class="d-inline-block position-relative text-secondary text-uppercase pb-2"
                >
                  تحتاج مساعدة؟
                </h6>
                <h1 class="display-4">أرسل لنا رسالة</h1>
              </div>
              <div class="contact-form">
                <form>
                  <div class="row">
                    <div class="col-6 form-group">
                      <input
                        type="text"
                        class="form-control border-top-0 border-right-0 border-left-0 p-0"
                        placeholder="اسم"
                        required="required"
                      />
                    </div>
                    <div class="col-6 form-group">
                      <input
                        type="email"
                        class="form-control border-top-0 border-right-0 border-left-0 p-0"
                        placeholder="البريد الإلكتروني"
                        required="required"
                      />
                    </div>
                  </div>
                  <div class="form-group">
                    <input
                      type="text"
                      class="form-control border-top-0 border-right-0 border-left-0 p-0"
                      placeholder="مسند"
                      required="required"
                    />
                  </div>
                  <div class="form-group">
                    <textarea
                      class="form-control border-top-0 border-right-0 border-left-0 p-0"
                      rows="5"
                      placeholder="رسالة"
                      required="required"
                    ></textarea>
                  </div>
                  <div>
                    <button class="btn btn-primary py-3 px-5" type="submit">
                      إرسال
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Contact End -->

      <!-- JavaScript Libraries -->
      <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
      <script src="{% static ''%}epoll/lib/easing/easing.min.js"></script>
      <script src="{% static ''%}epoll/lib/waypoints/waypoints.min.js"></script>
      <script src="{% static ''%}epoll/lib/counterup/counterup.min.js"></script>
      <script src="{% static ''%}epoll/lib/owlcarousel/owl.carousel.min.js"></script>

      <!-- Template Javascript -->
      <script src="{% static ''%}epoll/epoll/js/main.js"></script>
      {% endblock %}
    </div>
  </div>
</div>

Django/epoll/templates/epoll/layout.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static ''%}epoll/styles.css ">

    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8" />
    <title>وقيت باش تقيد</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta content="Free HTML Templates" name="keywords" />
    <meta content="Free HTML Templates" name="description" />

    <!-- Favicon -->
    <link href="{% static ''%}epoll/img/favicon.ico" rel="icon" />

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
        href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap"
        rel="stylesheet" />

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet" />

    <!-- Libraries Stylesheet -->
    <link href="lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static ''%}epoll/style.css" rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}">وقيت باش تقيد</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          {% if request.user.is_authenticated%}
            <a class="nav-item nav-link" href="{% url 'dashboard' %}">اللوحة الرئيسية</a>
            <a class="nav-item nav-link" href="{% url 'editProfile' %}">تعديل الملف الشخصي </a>
            <a class="nav-item nav-link" href="{% url 'changePassword'%}">غير كلمة السر</a>
            <a class="nav-item nav-link" href="{% url 'logout' %}">تسجيل خروج</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'login' %}">تسجيل الدخول</a>
            <a class="nav-item nav-link" href="{% url 'register' %}">إنشاء حساب</a>
          {% endif %}

        </div>
      </div>
    </nav>
  </div>
  <br/>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>

Django/epoll/templates/epoll/login.html
{% extends "epoll/layout.html" %} {% block content %}

<div class="jumbotron">
  {% if message %}
  <div class="alert alert-danger" role="alert">{{ message }}</div>
  {% endif %}

  <h2>تسجيل دخول</h2>
  <form action="." method="POST">
    {% csrf_token %}
    <div class="form-group">
      <label for="username">اسم المستخدم:</label>
      <input
        type="text"
        name="username"
        class="form-control"
        id="username"
        required
      />
    </div>
    <div class="form-group">
      <label for="password">كلمة المرور:</label>
      <input
        type="password"
        name="password"
        class="form-control"
        id="password"
        required
      />
    </div>

    <input type="submit" class="btn btn-primary btn-sm" value="تسجيل الدخول" />
  </form>
</div>

{% endblock %}

Django/epoll/templates/epoll/password.html
{% extends "epoll/layout.html" %}

{% block title %}Change Password{% endblock %}

{% block content %}
<div class="jumbotron">
  <h3>Password Change Form</h3>
  <form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% for field in form %}
      <div class="form-group">
        {% if field.errors %}
          {% for error in field.errors %}
            <ul>
              <li>{{error}}</li>
            </ul>
          {% endfor %}
        {% endif %}   
      </div>
    {% endfor %}
    <input type="submit" class="btn btn-sm btn-primary" value="Update">
  </form>
</div>

{% endblock %}

Django/epoll/templates/epoll/position.html
{% extends "epoll/layout.html" %} {%block content %}
<div class="jumbotron">
  <h2>مستجدات</h2>
  <ul>
    {% for i in obj %}
    <li><a href="{% url 'candidate' i.id %}">{{i.title}}</a></li>
    {% empty %}
    <p>No Positions Available</p>
    {% endfor %}
  </ul>
</div>
{% endblock %}

Django/epoll/templates/epoll/register.html
{% extends "epoll/layout.html" %} {% block title %}Registration{% endblock %}
{%block content %}
<div class="jumbotron">
  <h2>تسجيل</h2>
  {% if note %}
  <h3 class="text text-muted">{{note}}</h3>
  {% endif %}
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-group">{{ form.as_p }}</div>

    {% for field in form %}
    <div class="form-group">
      {% if field.errors %} {% for error in field.errors %}
      <ul>
        <li>{{error}}</li>
      </ul>
      {% endfor %} {% endif %}
    </div>
    {% endfor %}
    <input type="submit" class="btn btn-primary btn-sm" value="Sign Up" />
  </form>
</div>

{% endblock %}

Django/epoll/templates/epoll/results.html
{% extends "epoll/layout.html" %} {% block title %}Result Page{% endblock %}
{%block content %}
<h2 class="text-center">النتائج</h2>
<table class="table table-bordered table-sm text-center">
  <thead>
    <tr>
      <th>اسم المرشح</th>
      <th>المنصب</th>
      <th>مجموع التصويت</th>
    </tr>
  </thead>
  <tbody>
    {% for i in obj %}
    <tr>
      <td>{{ i.name }}</td>
      <td>{{ i.position }}</td>
      <td>{{ i.no_votes }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}